# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: File Generator

on: # yamllint disable-line rule:truthy
  push:
    branches: [ main ]
    paths: ["yaml/**.yaml"]

jobs:
  generate-hashes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        submodules: true
    - name: Set up Python 3.11
      uses: actions/setup-python@v4.5.0
      with:
        python-version: 3.11
    - name: Generating Files
      run: |
        python bin/gen-files.py
    - name: Commit generated data
      run: |
          git config --global user.name 'Github Actions';
          git config --global user.email 'robot@noreply.github.com';
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/magicsword-io/LOLDrivers;
          git add --all;
          if [ "`git diff --cached --numstat | wc -l`" != "0" ];
            then
              git commit -m "New hashes list generated by CICD";
              git push;
            else
              echo "No new modifications were made since previous commit";
          fi
