# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Validate YAMLs

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "*"
  pull_request:
    branches: [main]

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 3.11
      uses: actions/setup-python@v4.5.0
      with:
        python-version: 3.11
    - name: Install Poetry
      run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
    - name: Install dependencies with Poetry
      run: poetry install
    - name: Run YAML Checks
      run: poetry run python bin/yaml-checker.py
